### ISSUE TITLE
Remove material dependency

### ISSUE THREAD

**Issue by calvintam236** [frencojobs/typeweight#3]
Is it possible to make this package without `material` dependency (use `dart:ui`’s `FontWeight` value instead)? We are building an app that does not use `material` at all.

Ref: https://api.flutter.dev/flutter/dart-ui/FontWeight-class.html

**Comment by frencojobs** [comment]
Sorry for the delay, I just got back to OSS stuff. v2.0.1 should depend on `dart:ui` instead of material. 

Thank you very much for filing an issue.
